### PR TITLE
Ga/port

### PR DESCRIPTION
**Pull request by gaand**
Use nerd ports for consistency among tmeplates

### CODE REVIEW

**Comment by jrhorn424** [comment]
Does this actually change the listening port? I don't think it does, it only enables hot reloading on the nerd port.

**Comment by gaand** [comment]
I ran it successfully before pushing.

**Comment by jrhorn424** [comment]
@gaand I made a small change. If you don't approve I'll remove it. Otherwise, I'm ok with merging. Please ping me when you merge so I can make an announcement to my developers. Thanks!

**Comment by gaand** [comment]
Trying to limit it so the two that are present in all our template repos except `express-api-template`.

But, that's not a real thing.


Although I think we should update `express-api-template` to include `grunt server` as a standard command.

**Pull request merged**
